name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Lint, Typecheck, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript typecheck
        run: npm run typecheck

      - name: Run unit/integration tests (Vitest)
        run: npm run test

      - name: Run end-to-end tests (Playwright)
        run: |
          npx playwright install --with-deps
          npm run test:e2e

      - name: Build project
        run: npm run build